language: node_js
node_js:
  - "lts/*"
install:
  - yarn global add codecov
  - yarn install --production=false
script:
  - npm run travis
  - codecov
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  local-dir: "dist"
  allow-empty-commit: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: BALS
